version: '3'
services:
  emqx:
    image: "emqx/emqx:v4.1.1"
    ports:
      # host:container mqtt
      - "1883:1883"
      # host:container mqtts
      - "8883:8883"
      # host:container ws
      - "8083:8083"
      # host:container wss
      - "8084:8084"
      # host:container api
      - "8082:8080"
    volumes:
      # host:container mosquitto config
      - ./etc/emqx.conf:/opt/emqx/emqx.conf
    networks:
      - home_chat
  nginx:
    depends_on:
      - emqx
    image: "nginx:stable"
    ports:
      # host:container http port
      - "8080:8080"
    volumes:
      # host:container http config
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      # host:container app directory
      - ./build:/usr/share/nginx/html/home_chat:ro
    networks:
      - home_chat
networks:
  home_chat:
    external: true
